language: node_js
node_js:
- node
dist: trusty
sudo: false
cache: yarn
script:
- yarn run coveralls
env:
  global:
    secure: LMpVFst0Z8a9EMs0c0Hi4A+i1xFHrmUcAq5ggcKXfqAJ8iLMgQ/t0xwRI4FiIhtyjcVg8zaV6tyZcmd+HdwqMPys0Akec0X7QYCMBN+cbimGRXI2a2EpRWRidY7ImPi+2FluVmLQhxz5rItqRWrGSM7U8j64XSvjwSLa2zUkiEcbGGuYHHNIwkd2F+MN1UH7vPq7zFLPF2aJZuP1qn80scyBmM1ZGKv6aR3/BTSyzBZ1bqUPTrU0jwyZOcNUWoKXHmaoo20359kzHIApdBaErVMBC8fSiMh9z3v2SuEpTQATiE91lxDoAxnF0DOmbZ6qzYhQcuPRPSkNJgVW4fzROhgiY9MOqfTEGYRHGqIgnkDKkVscID8Y9VwKlpURStW8cEfc9DPG5k3Z2c1BaExGggaiyONewOheKUe2WXLEjQUJeWw7j+LnY7wG041zi0gPX7xvcMW00FrtLEeopJXTd1hQbVQsFHYicztSvJP5CvbO7Ct0Ktw/kRb1Z4mZNvbEm3mhktRD3T/LnIyPvJTLxVtECvlVh+Fviryo/IQFK7oatnS+w7xiQ2NY/v86ogM+6L63Es/pMltMgFGz0Ym2Yv+fyE/15na4f5kHILIX3Icv9GqqWLyuuff/XvsN68bnGDRP0KQ/BdFWc0+HA+zonYhyNz83E4gqVd/CMJ9aMhk=
